# debug docker local

services:
  debug:
    image: debug-container-image
    build: 
      context: .
    ports:
      - 80:80
      - 5678:5678

# run docker locally

# services:
#   app:
#     build: .
#     container_name: simple-python-server
#     command: gunicorn main:app --bind 0.0.0.0:80 --reload
#     ports:
#       - 8080:80
#     volumes:
#       - .:/app