name: Build and Deploy Docker

on:
  workflow_dispatch:
  
  push:
    branches: 
    - 'master'

defaults:
  run:
    working-directory: project/google_cloud_solution
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v2

    - name: Install gcloud Cli
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}
        export_default_credentials: true

    - name: build Docker Image
      env:
        GCP_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker europe-west3-docker.pkg.dev
        docker build -t europe-west3-docker.pkg.dev/$GCP_PROJECT/ml-docker-registry/ml_docker:latest .
        docker push europe-west3-docker.pkg.dev/$GCP_PROJECT/ml-docker-registry/ml_docker:latest
      

