name: Build and Deploy Docker

on:
  workflow_dispatch:

  push:
    branches: 
    - 'master'

defaults:
  run:
    working-directory: project/google_cloud_solution

permissions:
  contents: read
  id-token: write
  checks: write

env:
  GCP_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  IMAGE_NAME: europe-west3-docker.pkg.dev/$GCP_PROJECT/ml-docker-registry/ml_docker
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v2

    - name: Set current date as env variable
      run: echo "TARGET_VERSION=`echo $(date +'%Y-%m-%dT%H-%M-%S')`" >> $GITHUB_ENV

    - name: Install gcloud Cli
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}
        export_default_credentials: true

    - name: Configure Docker 
      run: |
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet
      
    - name: Build Docker
      runs: |
        docker build . -t $IMAGE_NAME:${{ env.TARGET_VERSION }}
    
    - name: Push Docker image
      run:  docker push $IMAGE_NAME:${{ env.TARGET_VERSION }}

    - name: Save target version for next job
      id: target_version_holder
      run: echo "TARGET_VERSION=${{ env.TARGET_VERSION }}" >> $GITHUB_OUTPUT
      

