name: Create Release

on:
  workflow_dispatch:
    input:
      source_version:
        required: true
        describtion: "docker image tag to release."
        type: string

      environment:
        required: true
        description: "environment to release image for."
        type: choice
        options:
          - prod
          - stage

env:
  DOCKER_IMAGE_DEV: europe-west3-docker.pkg.dev/bachlelor-ml/ml-docker-registry/ml_docker
  DOCKER_IMAGE_DEST: europe-west3-docker.pkg.dev/bachlelor-ml-${{ github.event.inputs.environment  }}/ml-docker-registry/ml_docker
  
jobs:
  pull_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Authenticate
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}
          export_default_credentials: true
      
      - name: Configure Docker 
        run: |
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

      - name: Pull Docker image from Dev
        run: docker pull ${{ env.DOCKER_IMAGE_DEV }}:${{ github.event.inputs.source_version }}

      - name: Authenticate to Destination
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          if: ${{ github.event.inputs.environment }} == prod
          project_id: ${{ secrets.GOOGLE_PROJECT }}-${{ github.event.inputs.environment }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_PROD_CREDENTIALS }}
          export_default_credentials: true

      - name: Authenticate to Destination
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          if: ${{ github.event.inputs.environment }} == stage
          project_id: ${{ secrets.GOOGLE_PROJECT }}-${{ github.event.inputs.environment }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_STAGE_CREDENTIALS }}
          export_default_credentials: true

      - name: Push Docker image
        run: |
          docker tag ${{ env.DOCKER_IMAGE_DEV }}:${{ github.event.inputs.source_version }} ${{ env.DOCKER_IMAGE_DEST }}:${{ github.event.inputs.source }}
          docker push ${{ env.DOCKER_IMAGE_DEST }}:${{ github.event.inputs.source }}